version: '3.6'

services:
  postgres:
    image: postgres:14.0-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network
  go-service:
    image: tienpvse/go-template
    container_name: go-service
    build: 
      context: .
    ports:
      - ${GO_PORT}:${GO_PORT}
    networks:
      - network
volumes:
  postgres_data:
    name: postgres_data
networks:
  network: